// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jamillosantos/lovr/internal/transport/http/websocket (interfaces: EntriesSearcher,WebsSocketConn)
//
// Generated by this command:
//
//	mockgen -package=websocket -destination=websocket_mock_test.go . EntriesSearcher,WebsSocketConn
//

// Package websocket is a generated GoMock package.
package websocket

import (
	context "context"
	reflect "reflect"

	entryreader "github.com/jamillosantos/lovr/internal/service/entryreader"
	gomock "go.uber.org/mock/gomock"
)

// MockEntriesSearcher is a mock of EntriesSearcher interface.
type MockEntriesSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockEntriesSearcherMockRecorder
	isgomock struct{}
}

// MockEntriesSearcherMockRecorder is the mock recorder for MockEntriesSearcher.
type MockEntriesSearcherMockRecorder struct {
	mock *MockEntriesSearcher
}

// NewMockEntriesSearcher creates a new mock instance.
func NewMockEntriesSearcher(ctrl *gomock.Controller) *MockEntriesSearcher {
	mock := &MockEntriesSearcher{ctrl: ctrl}
	mock.recorder = &MockEntriesSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntriesSearcher) EXPECT() *MockEntriesSearcherMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockEntriesSearcher) Search(arg0 context.Context, arg1 entryreader.SearchRequest) (entryreader.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1)
	ret0, _ := ret[0].(entryreader.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockEntriesSearcherMockRecorder) Search(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockEntriesSearcher)(nil).Search), arg0, arg1)
}

// MockWebsSocketConn is a mock of WebsSocketConn interface.
type MockWebsSocketConn struct {
	ctrl     *gomock.Controller
	recorder *MockWebsSocketConnMockRecorder
	isgomock struct{}
}

// MockWebsSocketConnMockRecorder is the mock recorder for MockWebsSocketConn.
type MockWebsSocketConnMockRecorder struct {
	mock *MockWebsSocketConn
}

// NewMockWebsSocketConn creates a new mock instance.
func NewMockWebsSocketConn(ctrl *gomock.Controller) *MockWebsSocketConn {
	mock := &MockWebsSocketConn{ctrl: ctrl}
	mock.recorder = &MockWebsSocketConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebsSocketConn) EXPECT() *MockWebsSocketConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWebsSocketConn) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWebsSocketConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWebsSocketConn)(nil).Close))
}

// ReadJSON mocks base method.
func (m *MockWebsSocketConn) ReadJSON(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadJSON", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadJSON indicates an expected call of ReadJSON.
func (mr *MockWebsSocketConnMockRecorder) ReadJSON(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadJSON", reflect.TypeOf((*MockWebsSocketConn)(nil).ReadJSON), data)
}

// WriteJSON mocks base method.
func (m *MockWebsSocketConn) WriteJSON(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteJSON", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteJSON indicates an expected call of WriteJSON.
func (mr *MockWebsSocketConnMockRecorder) WriteJSON(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteJSON", reflect.TypeOf((*MockWebsSocketConn)(nil).WriteJSON), data)
}
